# Generated by Django 2.1.1 on 2018-09-29 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180929_0631'),
        ('app', '0003_auto_20180928_0832'),
    ]

    operations = [
    ]
