# Generated by Django 2.1.1 on 2018-10-04 09:15

import app.views.CommonHelpers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180930_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='acc_number',
            field=models.CharField(default=app.views.CommonHelpers.get_unique_acc_number, max_length=16, unique=True, verbose_name='Account Number'),
        ),
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='card_number',
            field=models.CharField(default=app.views.CommonHelpers.get_unique_card_number, max_length=16, unique=True),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acc_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to='app.Address'),
        ),
        migrations.AlterField(
            model_name='pii',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pii_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
