# Generated by Django 2.1.1 on 2018-10-04 09:28

import app.views.CommonHelpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20181004_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(default=app.views.CommonHelpers.get_unique_card_number, max_length=16, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='card_number',
        ),
        migrations.AddField(
            model_name='card',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acc_card', to='app.Account'),
        ),
    ]
