# Generated by Django 2.1.1 on 2018-10-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20181004_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='address',
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Individual User'), (2, 'Merchant'), (3, 'Employee'), (4, 'Manager'), (5, 'Admin')], default=1),
        ),
    ]
