# Generated by Django 2.1.1 on 2018-10-15 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20181013_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_transaction', to=settings.AUTH_USER_MODEL),
        ),
    ]
