# Generated by Django 2.1.1 on 2018-10-15 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_transaction_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_transaction', to=settings.AUTH_USER_MODEL),
        ),
    ]
