# Generated by Django 2.1.1 on 2018-10-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20181016_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='model_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Account'), (2, 'Transaction')], null=True),
        ),
    ]
