# Generated by Django 2.1.1 on 2018-10-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_userrequest_model_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='for_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='model_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Account'), (2, 'Transaction'), (3, 'User')], null=True),
        ),
    ]
