# Generated by Django 2.1.1 on 2018-10-18 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20181018_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='from_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='request_from', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='model_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Account'), (2, 'Transaction'), (3, 'User Profile'), (4, 'PII')], null=True),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='to_user',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='request_to', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
