# Generated by Django 2.1.1 on 2018-10-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20181019_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pii',
            name='aadhar',
            field=models.CharField(max_length=12, unique=True, verbose_name='aadhar number'),
        ),
    ]
