# Generated by Django 2.1.1 on 2018-10-19 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20181019_0448'),
        ('app', '0022_auto_20181019_0416'),
    ]

    operations = [
    ]
