# Generated by Django 2.1.1 on 2018-10-19 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_merge_20181019_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
