# Generated by Django 2.1.1 on 2018-10-19 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20181019_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
