# Generated by Django 2.1.1 on 2018-10-19 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_userrequest_approved_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known_account', to='app.Account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
