# Generated by Django 2.1.1 on 2018-10-20 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_knownaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knownaccount',
            name='user',
            field=models.ForeignKey(limit_choices_to={'user_type__in': (1, 2)}, on_delete=django.db.models.deletion.CASCADE, related_name='known_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
