# Generated by Django 2.1.1 on 2018-10-20 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20181020_0535'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='knownaccount',
            unique_together={('user', 'account')},
        ),
    ]
