# Generated by Django 2.1.1 on 2018-10-24 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20181024_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantpaymentaccount',
            name='merchant_user',
            field=models.ForeignKey(limit_choices_to={'user_type': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
