# Generated by Django 2.1.1 on 2018-10-30 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_publickey'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edited_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='request_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Create'), (2, 'Read'), (3, 'Update'), (4, 'Delete'), (5, 'Complete Update'), (6, 'Complete Delete')], null=True),
        ),
    ]
